# Generated by Django 6.1.1 on 2026-10-07 09:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad_base', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ingredientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('instrucciones', models.TextField()),
                ('tiempo_preparacion', models.PositiveIntegerField(help_text='Tiempo en minutos')),
                ('dificultad', models.CharField(choices=[('facil', 'Facil'), ('media', 'Media'), ('dificil', 'Dificil')], default='media', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='proyecto.categoria')),
            ],
            options={
                'db_table': 'recetas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenReceta',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.URLField(max_length=500)),
                ('texto_alternativo', models.CharField(blank=True, max_length=255)),
                ('es_principal', models.BooleanField(default=False)),
                ('receta', models.ForeignKey(db_column='id_receta', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='proyecto.receta')),
            ],
            options={
                'db_table': 'imagenes_receta',
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True)),
                ('receta', models.ForeignKey(db_column='id_receta', on_delete=django.db.models.deletion.CASCADE, related_name='guardado_por', to='proyecto.receta')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='proyecto.usuario')),
            ],
            options={
                'db_table': 'favoritos',
            },
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unidad', models.CharField(max_length=50)),
                ('opcional', models.BooleanField(default=False)),
                ('ingrediente', models.ForeignKey(db_column='id_ingrediente', on_delete=django.db.models.deletion.CASCADE, related_name='receta_ingredientes', to='proyecto.ingrediente')),
                ('receta', models.ForeignKey(db_column='id_receta', on_delete=django.db.models.deletion.CASCADE, related_name='receta_ingredientes', to='proyecto.receta')),
            ],
            options={
                'db_table': 'receta_ingrediente',
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(related_name='recetas', through='proyecto.RecetaIngrediente', to='proyecto.ingrediente'),
        ),
        migrations.AddField(
            model_name='receta',
            name='favoritos',
            field=models.ManyToManyField(related_name='recetas_favoritas', through='proyecto.Favorito', to='proyecto.usuario'),
        ),
        migrations.AddField(
            model_name='receta',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='proyecto.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('puntuacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('receta', models.ForeignKey(db_column='id_receta', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='proyecto.receta')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='proyecto.usuario')),
            ],
            options={
                'db_table': 'comentarios',
                'ordering': ['-fecha_comentario'],
            },
        ),
        migrations.AddConstraint(
            model_name='recetaingrediente',
            constraint=models.UniqueConstraint(fields=('receta', 'ingrediente'), name='pk_receta_ingrediente'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'receta'), name='pk_favoritos'),
        ),
    ]
