# Generated by Django 6.1.1 on 2026-10-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_receta_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='imagen',
        ),
    ]
